# -*- coding: utf-8 -*-
"""Calculate Exposure.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7s1SI5DqrXrdHmxxNBvCEDEm32PbjLw
"""

def calculate_percentage(obtained, total):
  return (obtained/total)*100

medicare_spend = float(input("Enter total Medicare Part D spend: "))
total_revenue = float(input("Enter total revenue: "))

percentage = calculate_percentage(medicare_spend, total_revenue)
print(f"Total Medicare Part D Exposure: {percentage:,.1f}%")
